# Arrays

In [2]:
import numpy as np

In [3]:
np.array([1,2,3,4,5])

array([1, 2, 3, 4, 5])

In [4]:
np.zeros(4)

array([0., 0., 0., 0.])

In [5]:
# And even an array that contains a range of evenly spaced intervals.
# To do this, you will specify the first number, last number, and the step size.
np.arange(0,8.1)

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [6]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.linspace(0,10,num=5) 
#You can also use np.linspace() to create an array with values that are spaced linearly in a specified interval:

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

# Specifying your data type

In [8]:
# While the default data type is floating point (np.float64), 
# you can explicitly specify which data type you want using the dtype keyword.

In [9]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

# Adding, removing, and sorting elements
- This section covers np.sort(), np.concatenate()

In [10]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8]) #You can quickly sort the numbers in ascending order with:

In [11]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8]) #You can concatenate them with np.concatenate().

In [13]:
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

# Can you reshape an array?

In [14]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [15]:
# You can use reshape() to reshape your array. For example, you can reshape 
# this array to an array with three rows and two columns:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


# How to convert a 1D array into a 2D array (how to add a new axis to an array)
- This section covers np.newaxis, np.expand_dims

In [16]:
# You can use np.newaxis and np.expand_dims to increase the dimensions of your existing array.

# Using np.newaxis will increase the dimensions of your array by one dimension
# when used once. This means that a 1D array will become a 2D array, a 2D array will become a 3D array, and so on.

In [17]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [18]:
a2 = a[np.newaxis, :] #You can use np.newaxis to add a new axis
a2.shape

(1, 6)

In [44]:
# You can explicitly convert a 1D array with either a row vector or a column vector using np.newaxis.
# For example, you can convert a 1D array to a row vector by inserting an axis along the first dimension:


In [45]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [46]:
# You can also expand an array by inserting a new axis at a specified position with np.expand_dims.

In [47]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [48]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [49]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

# If you want to select values from your array that fulfill certain conditions, it’s straightforward with NumPy.

In [50]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [51]:
print(a[a < 5])

[1 2 3 4]


In [52]:
five_up = (a >= 5)
print(a[five_up])

[ 5  6  7  8  9 10 11 12]


In [53]:
divisible_by_2 = a[a%2==0]
print(divisible_by_2)

[ 2  4  6  8 10 12]


In [54]:
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [55]:
five_up = (a > 5) | (a == 5)
print(five_up)

[[False False False False]
 [ True  True  True  True]
 [ True  True  True  True]]


# 1d array

In [56]:
a=np.array([1,2,3])

In [57]:
a

array([1, 2, 3])

In [61]:
a=np.array([[1,2,3],[4,5,6],[3,4,6]])

In [62]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [3, 4, 6]])


# Array functions

In [19]:
a=np.array([2,1,3,4,7,6,4])

In [20]:
np.sort(a)

array([1, 2, 3, 4, 4, 6, 7])

In [25]:
b=np.array([1,6,4,3,2,5,2,1])

In [27]:
np.concatenate((a,b))

array([2, 1, 3, 4, 7, 6, 4, 1, 6, 4, 3, 2, 5, 2, 1])

In [28]:
a=np.array([[1,2],[3,4]])

In [29]:
b=np.array([[2,3],[2,4]])

In [34]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [2, 3],
       [2, 4]])

In [35]:
np.concatenate((a,b),axis=1)

array([[1, 2, 2, 3],
       [3, 4, 2, 4]])

In [36]:
a.ndim

2

In [37]:
a.shape

(2, 2)

In [39]:
a.size

4

In [42]:
a=np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [43]:
a*5

array([ 5, 10, 15, 20, 25])

In [44]:
a+2

array([3, 4, 5, 6, 7])

In [45]:
a-2

array([-1,  0,  1,  2,  3])

In [47]:
a.sum()

15

In [48]:
a.mean()

3.0