In [1]:
import numpy as np

In [2]:
arr1=np.array([1,2,3,4,5])

In [3]:
arr1

array([1, 2, 3, 4, 5])

# indexing

In [4]:
arr1[0]

1

In [5]:
arr1[1]

2

In [6]:
arr1[-1]

5

In [8]:
arr1[2]

3

In [9]:
arr1[-2]

4

# slicing

In [10]:
arr1

array([1, 2, 3, 4, 5])

In [11]:
arr1[::]

array([1, 2, 3, 4, 5])

In [12]:
arr1[0::2]

array([1, 3, 5])

In [13]:
arr1[-1::-1]

array([5, 4, 3, 2, 1])

In [14]:
arr1[-1:-6:-2]

array([5, 3, 1])

In [15]:
arr1[::-2]

array([5, 3, 1])

In [16]:
arr1

array([1, 2, 3, 4, 5])

In [17]:
arr1[-1::]

array([5])

In [18]:
arr1[-1:0:-2]

array([5, 3])

# Slicing using list as position

In [19]:
arr1

array([1, 2, 3, 4, 5])

In [20]:
l1=[1,4]

In [21]:
arr1[l1]

array([2, 5])